### ISSUE TITLE
DCS-BIOS 2.7.16 breaks console app?

### ISSUE THREAD

**Issue by rhaleblian** [charliefoxtwo/TouchDCS#18]
I can post more detailed logs later, time permitting, but in lieu of that:
The console app raises an exception when starting up, about a duplicate key being added.
Dropping into a debugger it looks like it happens when the Mirage F-1 is discovered.
I ran a tweaked codebase that skips that aircraft and the exception is avoided.

2.7.16 adds the Mirage F-1.

The previous DCS-BIOS release (2.7.14) does not exhibit the problem.

**Comment by rhaleblian** [comment]
Otherwise, this app is working for me and I was building little control panels for the A-10C the other day.  Neato!

**Comment by charliefoxtwo** [comment]
> The console app raises an exception when starting up, about a duplicate key being added.

It should only warn, not throw. Does the app crash, or just warn? If it just writes the warn log, it's fine (touchdcs will skip it) and the duplicate key should be reported to https://github.com/DCSFlightpanels/dcs-bios as it's a bug on their end where they are using the same key twice in the same aircraft, which can't possibly work.

**Comment by rhaleblian** [comment]
I'll rephrase -- the user gets a complaint message, the app keeps running, and things appeared non responsive to this user.

Understanding the incoming data isn't TouchDCS' purview, I for one, wouldn't pass this back to dcs-bios without some information, like what key we're talking about.  In the readable configuration, I don't see aircraft keys being duplicated at all, let alone the F-1.  Again, a relevant message wants capturing.

**Comment by charliefoxtwo** [comment]
TouchDCS should log the key in question, no? I've filed quite a few bugs against the dcs-bios repo just from my log messages so I'm pretty sure it does. Can you send me the log file (assuming you're running 0.3.1) or a screenshot of the console so I can better understand the issue?

Separately, you're right that perhaps the warn message could be reworded to indicate to the user that the app will continue to run, but they may have issues with that specific item.

**Comment by rhaleblian** [comment]
It's sad.  This issue started off on the wrong foot for exactly the reason it claimed it was not well-posed issue.
I'm reporting at least one wrong thing.
![image](https://user-images.githubusercontent.com/94912/186989724-71107341-0fa5-4b4c-9e14-4dc0fe46b756.png)
I'll collect up the right info and an example branch.

**Comment by charliefoxtwo** [comment]
This is not the issue I thought it was. Something else appears to be going on here. The application is definitely crashing, and it should not. I'll need to investigate.

The warn logs you see are expected, but for a different reason. The dcs-bios developer insists on these json files, which are used as input for dcs-bios, be in the docs folder instead 🤷

**Comment by charliefoxtwo** [comment]
@rhaleblian would you be able to try out this new release and let me know if it fixes the issue (and still works as expected everywhere else)? https://github.com/charliefoxtwo/TouchDCS/releases/tag/latest

**Comment by rhaleblian** [comment]
yep, I should be on my workstation today in fact.

**Comment by rhaleblian** [comment]
Yes, that release fixes the issue.  Also checked basic function with my A-10C MFD layout and that's still working fine.

**Comment by charliefoxtwo** [comment]
Alright sweet. I'll leave it as a prerelease for a few more days in case something comes up.

**Comment by rhaleblian** [comment]
We feel good about this ya?  Closable?

**Comment by charliefoxtwo** [comment]
oh yeahhhhh I actually released that so yeah I feel good about it, thanks for reminding me (and thanks for opening the issue in the first place!)
